# Generated by Django 3.0.5 on 2021-05-15 12:54

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='default.jpg', upload_to='snapshots')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default.mp4', upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('snapshot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Snapshot')),
                ('videofile', models.OneToOneField(default=catalog.models.get_default_videofile, on_delete=django.db.models.deletion.CASCADE, to='catalog.VideoFile')),
            ],
        ),
    ]
