# Generated by Django 3.0.5 on 2021-05-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='snapshot'),
        ),
        migrations.AddField(
            model_name='video',
            name='snapshot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Snapshot'),
        ),
    ]
