# Generated by Django 3.0.5 on 2021-05-21 21:35

from django.db import migrations, models
import django.db.models.deletion
import video.models.video


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCodec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCodec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views_count', models.BigIntegerField()),
                ('liked_count', models.BigIntegerField()),
                ('disliked_count', models.BigIntegerField()),
                ('description', models.TextField()),
                ('datetime_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('file', models.ImageField(null=True, upload_to=video.models.video.videothumbnail_path)),
                ('mime_type', models.CharField(max_length=127)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('videounits', models.ManyToManyField(to='video.VideoUnit')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('file', models.FileField(upload_to=video.models.video.videofile_path)),
                ('mime_type', models.CharField(max_length=127)),
                ('duration', models.DurationField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
                ('audio_codec', models.ManyToManyField(to='video.AudioCodec')),
                ('video_codec', models.ManyToManyField(to='video.VideoCodec')),
            ],
        ),
    ]
