# Generated by Django 3.0.5 on 2021-05-18 12:30

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('file', models.FileField(upload_to=video.models.videofile_path)),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
            ],
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('file', models.ImageField(null=True, upload_to=video.models.videothumbnail_path)),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('videounits', models.ManyToManyField(to='video.VideoUnit')),
            ],
        ),
    ]
