# Generated by Django 3.0.5 on 2021-05-17 13:40

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('file', models.ImageField(null=True, upload_to=video.models.videothumbnail_path)),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to=video.models.videofile_path),
        ),
        migrations.AlterField(
            model_name='videounit',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
