# Generated by Django 3.0.5 on 2021-05-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('file', models.ImageField(null=True, upload_to='thumbnails')),
                ('videounit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video.VideoUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
