# Generated by Django 3.0.5 on 2021-05-16 14:58

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210516_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to=video.models.videofile_path),
        ),
        migrations.AlterField(
            model_name='videothumbnail',
            name='file',
            field=models.ImageField(null=True, upload_to=video.models.videothumbnail_path),
        ),
    ]
